### MyNotes configuration ###

# Rocket web server config
[default]
port = 12345
workers = 2
ident = false

# MyNotes app config
[default.app]
# markdown content folder
markdown_folder = "test/md"

[default.app.users]
# authorized users: user name and password mapping
user = "password"
